/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.harding;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author T RICH
 */
public class AddModifyContactForm extends javax.swing.JFrame
{
    MainForm parent = null;
    private int type;
    /**
     * Creates new form AddContactForm
     */
    public AddModifyContactForm(MainForm parent)
    {
        initComponents();
        this.parent = parent;
        this.rootPane.setDefaultButton(okButton);
        type = 0;
        
        this.getContentPane().setBackground(Color.darkGray);
        
        setTitle("Add Contact");
        
        // http://www.coderanch.com/t/333523/GUI/java/JFrame-position-size
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int sWIDTH = screenSize.width;
        int sHEIGHT = screenSize.height;
        setLocation(new Point(sWIDTH/2 - getWidth()/2, sHEIGHT/2 - getHeight()/2));
    }
    
    public AddModifyContactForm(MainForm parent, String first, String last, String preferred, String email)
    {
        initComponents();
        this.parent = parent;
        this.rootPane.setDefaultButton(okButton);
        FirstNameTextBox.setText(first);
        LastNameTextBox.setText(last);
        PreferredNameTextBox.setText(preferred);
        EmailTextBox.setText(email);
        type = 1;
        
        this.getContentPane().setBackground(Color.darkGray);
        
        setTitle("Modify Contact");
        
        // http://www.coderanch.com/t/333523/GUI/java/JFrame-position-size
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int sWIDTH = screenSize.width;
        int sHEIGHT = screenSize.height;
        setLocation(new Point(sWIDTH/2 - getWidth()/2, sHEIGHT/2 - getHeight()/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        PreferredNameTextBox = new javax.swing.JTextField();
        LastNameTextBox = new javax.swing.JTextField();
        FirstNameTextBox = new javax.swing.JTextField();
        EmailTextBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("OK");
        okButton.setFocusCycleRoot(true);
        okButton.setSelected(true);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Preferred Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email Address");

        cancelButton.setText("Cancel");
        cancelButton.setDefaultCapable(false);
        cancelButton.setFocusCycleRoot(true);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameTextBox)
                    .addComponent(LastNameTextBox)
                    .addComponent(PreferredNameTextBox)
                    .addComponent(EmailTextBox))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(FirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(LastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PreferredNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getAddModifyType()
    {
        return type;
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        // TODO add your handling code here:
        if(type == 0)
        {
            if (!parent.AddRowFromDialog(FirstNameTextBox.getText(), LastNameTextBox.getText(), PreferredNameTextBox.getText(), EmailTextBox.getText()))
            {
                //JOptionPane.showMessageDialog(this, "Could not add contact.\nDuplicate email address.", "Error", JOptionPane.WARNING_MESSAGE);
                Object[] options = {"OK",
                        "Cancel"};
                int n = JOptionPane.showOptionDialog(this,
                    "Could not add contact.\n"
                        + "Duplicate email address.\n"
                        + "Would you like to modify contact?",
                    "Error",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[1]);
                if (n == 1)
                {
                    this.dispose();
                }
            }
            else
            {
                this.dispose();
            }
        }
        else
        {
            if (!parent.ModifyRowFromDialog(FirstNameTextBox.getText(), LastNameTextBox.getText(), PreferredNameTextBox.getText(), EmailTextBox.getText()))
            {
                //JOptionPane.showMessageDialog(this, "Could not add contact.\nDuplicate email address.", "Error", JOptionPane.WARNING_MESSAGE);
                Object[] options = {"OK",
                        "Cancel"};
                int n = JOptionPane.showOptionDialog(this,
                    "Could not Modify contact.\n"
                        + "Duplicate email address.\n"
                        + "Would you like to modify email?",
                    "Error",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[1]);
                if (n == 1)
                {
                    this.dispose();
                }
            }
            else
            {
                this.dispose();
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AddModifyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AddModifyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AddModifyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AddModifyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        //java.awt.EventQueue.invokeLater(new Runnable()
        //{

        //    public void run()
        //    {
        //        new AddContactForm().setVisible(true);
        //    }
        //});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextBox;
    private javax.swing.JTextField FirstNameTextBox;
    private javax.swing.JTextField LastNameTextBox;
    private javax.swing.JTextField PreferredNameTextBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
